version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
    - ${DASHBOARD_PORT}:4567
    command: bundle exec ruby app.rb
    environment:
    - DASHBOARD_URL=${BASE_URL}:${DASHBOARD_PORT}
    - CLOUDCMD_URL=${BASE_URL}:${CLOUDCMD_PORT}
    - PLEX_URL=${BASE_URL}:${PLEX_PORT}
    - TRANSMISSION_TV_URL=${BASE_URL}:${TRANSMISSION_TV_PORT}
    - TRANSMISSION_MOVIES_URL=${BASE_URL}:${TRANSMISSION_MOVIES_PORT}
  plex:
    image: "linuxserver/plex"
    environment:
    - VERSION=latest
    - TZ=Australia/Melbourne
    volumes:
    - ./data/config:/config
    - ${CINEMA_DIR}:/cinema
    - ${TV_DIR}:/tv
    ports:
    - ${PLEX_PORT}:32400
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 1G
  cloudcmd:
    image: "coderaiser/cloudcmd"
    volumes:
    - ${BASE_TRANSMISSION_DIR}:/downloads
    ports:
    - ${CLOUDCMD_PORT}:8000
  transmission_tv:
    image: "linuxserver/transmission"
    volumes:
    - ${TV_CONFIG_DIR}:/config
    - ${BASE_TRANSMISSION_DIR}/TV:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    - TR_DOWNLOAD_DIR=/downloads
    ports:
    - ${TRANSMISSION_TV_PORT}:9091
    - "51413:51413"
  transmission_movies:
    image: "linuxserver/transmission"
    volumes:
    - ${CINEMA_CONFIG_DIR}:/config
    - ${BASE_TRANSMISSION_DIR}/Movies:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    - TR_DOWNLOAD_DIR=/downloads
    - TR_IDLE_SEEDING_LIMIT_ENABLED=true
    - TR_IDLE_SEEDING_LIMIT=600
    - TR_RATIO_LIMIT_ENABLED=true
    - TR_RATIO_LIMIT=4
    ports:
    - ${TRANSMISSION_MOVIES_PORT}:9091
    - "51414:51413"
