version: '3'
services:
  app_one:
    build: ./app_one
    ports:
    - "4567:4567"
  plex:
    image: "linuxserver/plex"
    environment:
    - VERSION=latest
    - TZ=America/New_York
    ports:
    - "32400:32400"
  nginx:
    image: "nginx:1.15.3"
    volumes:
    - ./nginx/config:/etc/nginx
    ports:
    - "80:80"
  transmission:
    image: "linuxserver/transmission"
    volumes:
    - ./transmission/config:/config
    - ${BASE_TRANSMISSION_DIR}/TV:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    ports:
    - "9091:9091"
    - "51413:51413"
  transmission_movies:
    image: "linuxserver/transmission"
    volumes:
    - ./transmission/config:/config
    - ${BASE_TRANSMISSION_DIR}/Movies:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    ports:
    - "9092:9091"
    - "51414:51413"