version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
    - ${DASHBOARD_PORT}:4567
    environment:
    - DASHBOARD_URL=${BASE_URL}:${DASHBOARD_PORT}
    - CLOUDCMD_URL=${BASE_URL}:${CLOUDCMD_PORT}
    - PLEX_URL=${BASE_URL}:${PLEX_PORT}
    - TRANSMISSION_TV_URL=${BASE_URL}:${TRANSMISSION_TV_PORT}
    - TRANSMISSION_MOVIES_URL=${BASE_URL}:${TRANSMISSION_MOVIES_PORT}
  plex:
    image: "linuxserver/plex"
    environment:
    - VERSION=latest
    - TZ=Australia/Melbourne
    ports:
    - ${PLEX_PORT}:32400
  cloudcmd:
    image: "coderaiser/cloudcmd"
    volumes:
    - ${BASE_TRANSMISSION_DIR}:/downloads
    ports:
    - ${CLOUDCMD_PORT}:8000
  transmission_tv:
    image: "linuxserver/transmission"
    volumes:
    - ./transmission/config:/config
    - ${BASE_TRANSMISSION_DIR}/TV:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    ports:
    - ${TRANSMISSION_TV_PORT}:9091
    - "51413:51413"
  transmission_movies:
    image: "linuxserver/transmission"
    volumes:
    - ./transmission/config:/config
    - ${BASE_TRANSMISSION_DIR}/Movies:/downloads
    environment:
    - PGID=0
    - PUID=0
    - TZ=AEST
    ports:
    - ${TRANSMISSION_MOVIES_PORT}:9091
    - "51414:51413"